baseURL = "https://www.kevinbarroga.me/tl/"			# Site's URL
title = "Training Log"								# Site's Name
theme = "manis"
# copyright = "&copy; 2017 Kevin Barroga"	# Copyright notice. Note: You can use HTML tag here
copyright = ""	# Copyright notice. Note: You can use HTML tag here
pluralizeListTitles = false
paginate = 10								# Minimum number of item before paginate navigation show up
canonifyURL = true
disqusShortname = "kevbarroga"                        # Your disqus shortname

[taxonomies]
	tag = "tags"


[params]
	debugCSS = true                        # If false, use minified CSS (ui.min.css)
	disqusSections = ["blog"]               # list of section support disqus comments
	# Site meta description
	description = ""
	tagline = ""   # Site's Tagline (Subtitle or Keyword)
	themeAttrib = false                      # If true give attribution to this theme
	licenseURL = ""           # URL to license file, can be outside of your domain

	# 404 Configuration
	head404 = "Sorry, I can find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	colorTheme = "#33ba91"                  # Color of your website
	latestCount = 5                         # Maximum number of item in Latest Posts or Works
	faviconImg = ""                         # Path to site's favicon image
	dateFmt = "Mon, 02 Jan 2006"                # Date format in item list

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "kevbarroga@gmail.com"
	github = "https://github.com/kevbarroga/"
	twitter = "https://twitter.com/kevbarroga"


# Language Configuration
defaultContentLanguage = "en"
# Edit this if you want to translate your blog
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1
